server:
  port: 8087
spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pankaj370378/micro-service-config
          clone-on-start: true
